### PR TITLE
Remove a bunch of no longer used files

### PR DESCRIPTION
**Pull request by marcelvoss**
Hello, hello.

In an attempt of starting to help cleaning up things, I went on started out searching for things that we no longer use or need. Part of that was realizing we still ship a category on UIActionSheet (something that has been deprecated and replaced years ago). 

I double and tripple checked and these things are definitely not in use anymore and there are better alternatives by now.

### CODE REVIEW

**Comment by mrjschulte** [comment]
Hi @marcelvoss ! Thanks for taking a look at this. 

Have you had a chance to build and test these changes out on tvOS? 

It looks like the bridging header removal items are also part of #1477 and both of these PR's don't build for tvOS as a result.

**Review by mrjschulte — CHANGES_REQUESTED** [review]
Hi, could you please also try and build this for tvOS? Currently it doesn't build on tvOS.

**Comment by marcelvoss** [comment]
Hi,

my bad. I kinda forgot about the fact that tvOS is a thing as well. Will revise this and re-request a review. Thanks!

**Comment by mrjschulte** [comment]
Great. Thanks so much!

**Comment by mrjschulte** [comment]
Hi @marcelvoss, we wanted to check in and ask if you had had any chance of taking a look at why tvOS breaks with this PR?

**Comment by marcelvoss** [comment]
Hi @mrjschulte,

I've been quite busy since my vacation has been over and haven't had a chance coming back to this until now. Pushed a fix. Simply forgot removing an import from the tvOS target's bridging header. I'm also unable to currently build the tvOS target, so that makes it a bit more difficult. 😣 

Also, could you next time please not merge develop into my branch? That makes it way more difficult to address/edit the commit in the history and also messes with my commit history (rather rebase from develop, avoid a merge commit that is not necessary and allows for easier editing). Removed your commit.

**Comment by mrjschulte** [comment]
Great stuff, thanks @marcelvoss . We'll take a look and merge accordingly. We'll keep the develop merge off of your branch in the future as well :)

**Review by mrjschulte — APPROVED** [review]

**Pull request merged**
