### PR TITLE
Fix some minor issues when building PVMednafen for devices

### PR DESCRIPTION
**Pull request by cheif**
This should make it possible to build to device again.

### CODE REVIEW

**Comment by james-rantmedia** [comment]
Just had time to look at the changes for this one and it seems the main change is the removal of the SuperFX implementation from the compilation steps? Does that mean any ROMs that require SuperFX emulation won't work when using Mednafen as the SNES core?

**Comment by cheif** [comment]
Exactly, but we’re already commenting out a bunch of stuff in the snes_faust core, so I’m not sure that it’ll work anyway. I’m also pretty sure that the superfx implementation is new in mednafen 1.24, so we’re not loosing anything.

**Comment by jasarien** [comment]
Another thing I thought about overnight is that we're making a lot of changes to Mednafen itself to make it work within the confines of Provenance and/or Xcode... won't this make it more difficult to update Mednafen again in the future? Are the required changes being documented?

**Comment by cheif** [comment]
Yeah, I created a UPDATING.md earlier with a description, but it’s not complete I’m afraid. I think a good way forward is to make sure CI builds everything, then we can catch things like this earlier at least.

**Comment by jasarien** [comment]
Tested this today, it works to enable me to archive a build from scratch if I combine it with removing some of the static asserts in `MednafenGameCore.mm` I'm not sure why they still fail (all the compiler defines seem to have the correct sizes for the types, but they still fail, as they all seem to be `8`, when they're defined as `1`, `2` or `4` for their respective types, etc.). 

I'll merge this one and then add my removal of the static asserts.

**Pull request merged**
