### PR TITLE
Project file and other minor fixes

### PR DESCRIPTION
**Pull request by dnicolson**
### What does this PR do
This pull request fixes some grammar, orphaned file references and other fixes.

### Where should the reviewer start
Look at each commit individually.

### How should this be manually tested
Run Carthage with [this fix](https://github.com/Carthage/Carthage/issues/3019#issuecomment-665136323) with Xcode 12.

### CODE REVIEW

**Review by cheif — APPROVED** [review]
Looks like a great cleanup!

**Review by james-rantmedia — APPROVED** [review]

**Review by jasarien — APPROVED** [review]

**Review by mrjschulte — APPROVED** [review]

**Comment by mrjschulte** [comment]
Hi @dnicolson, it looks like there is a problem w this Pr. We've tried to build it out on both iOS and tvOS but run into the following insta-crash when the app is built successfully and is attempting to run on the device for the first time:

_dyld: Library not loaded: @rpath/Reachability.framework/Reachability
  Referenced from: /private/var/containers/Bundle/Application/5DB0F0DB-B5CF-4091-A5B8-51B02B7A3DFB/Provenance.app/Provenance
  Reason: image not found
(lldb)_ 

Any chance you can take a look at this and see if this issue can be fixed? We'd love to get your clean-ups and fixes into the repo.

**Comment by dnicolson** [comment]
Please try again @mrjschulte. Removing seemingly invalid Carthage references in https://github.com/Provenance-Emu/Provenance/commit/4796624230434c71a5c21594fabd35cbb6d2bf17 caused the issue. I also added a shebang to the Carthage script in https://github.com/Provenance-Emu/Provenance/pull/1443/commits/3cc677de917886a1c7747090706c8152d3f0926d so that it works with the fish shell.

**Comment by mrjschulte** [comment]
> Please try again @mrjschulte. Removing seemingly invalid Carthage references in [4796624](https://github.com/Provenance-Emu/Provenance/commit/4796624230434c71a5c21594fabd35cbb6d2bf17) caused the issue. I also added a shebang to the Carthage script in [3cc677d](https://github.com/Provenance-Emu/Provenance/commit/3cc677de917886a1c7747090706c8152d3f0926d) so that it works with the fish shell.

Great, let me repull and build again! Thanks for taking a look @dnicolson !

**Comment by mrjschulte** [comment]
Unfortunately it's still a no-go as-is here @dnicolson ,doing a clean Pull and building the Pr from scratch I can get a successful build in Xcode but upon attempting to launch the build on the iOS device I get the following hard crash:

__dyld: Library not loaded: @rpath/PVTGBDual.framework/PVTGBDual
  Referenced from: /private/var/containers/Bundle/Application/DEA7BD6F-9D72-4929-BEE6-00916936C0FE/Provenance.app/Provenance
  Reason: image not found
(lldb)__ 

And insta-crash. 

Oddly enough, this Pr builds and subsequently runs just fine on tvOS.

So, taking a deeper look, it turns out that for iOS the framework was set to "do not embed". Switching this state to "Embed & Sign" just like it's set in tvOS and for the other Cores, will fix this insta-crash. 

Could you please address this in your PR and let me know with an @mrjschulte when it's good to repull and test?

**Comment by dnicolson** [comment]
The PVTGBDual framework was not embedded in the iOS build, I'm not sure it was a rebase issue but I verified that it works on an iOS device now. Can you please take another look @mrjschulte?

**Comment by mrjschulte** [comment]
Thanks for the quick fix @dnicolson ! Merging now.

**Pull request merged**
