### PR TITLE
Hide collapse button on tvOS

### PR DESCRIPTION
**Pull request by dnicolson**
### What does this PR do
This pull request hides the collapse buttons on tvOS as they do not perform a function as they do on iOS.

### Screenshots (important for UI changes)
Before:
Screen Shot 2020-12-08 at 19 30 33

After:
Screen Shot 2020-12-08 at 19 28 34

### Questions
Should the collapse functionality be made available on tvOS? It is actually possible for the collapse buttons to work on tvOS, it requires the following conditions/changes though:
- A section has to contain enough ROMs to be able to select the button on the right
- Duplicating the [header.collapseButton.rx.tap](https://github.com/Provenance-Emu/Provenance/blob/70f7720233561371362761f75c814a1d0806f442/Provenance/Game%20Library/UI/Game%20Library/CollectionViewController/PVGameLibraryViewController.swift#L314) functionality but replacing `tap` with `primaryAction`
- Removing the following function: https://github.com/Provenance-Emu/Provenance/blob/70f7720233561371362761f75c814a1d0806f442/Provenance/Game%20Library/UI/Game%20Library/CollectionViewController/PVGameLibraryViewController+CollectionView.swift#L84

### CODE REVIEW

**Comment by cheif** [comment]
I totally agree with removing this, but I also think that we might want to make it work instead? We could probably modify the `collapsible` state of a section to take number of items into account, and then maybe make a convenience-thing calling tap or primaryAction depending on platform. 
There's so many #if-s in the code base already, would be nice to remove some of them, rather than adding more 😀

Anyway, great work and a really nice attention to detail!

**Comment by mrjschulte** [comment]
I'd be totally up for making it work as well, that's why I put them back in there for the phase01 of the tvOS Ui updates.

**Comment by dnicolson** [comment]
@mrjschulte It appears that these buttons have been the same for years?

The collapse button has no focus state, perhaps if the whole section header had one it might work. Right now the button is mostly inaccessible, if you turn on `UIFocusLoggingEnabled` you can see that every 7th item can access the button. Maybe this is something that can be fixed with https://github.com/Provenance-Emu/Provenance/issues/1456.

**Comment by mrjschulte** [comment]
Yeah, noticed that the chevron has no real focus state. Ideally I think we'd like to expand the tvOS Ux to allow for the Chevron to "collapse/expand" the various System categories.

**Comment by dnicolson** [comment]
I got something crude working on this [branch](https://github.com/Provenance-Emu/Provenance/compare/develop...dnicolson:section-headers-focusable?expand=1), basically the section headers are focusable and the chevron is triggered on select. I'm sure there's a better way or doing it but that's the basic concept.

**Comment by mrjschulte** [comment]
Yup, it works as advertised but do you think we could limit the "focusable area" to only be the "chevron" and not the entire section header? 

Right now the entire section header "lights up" as you stated and it kinda shows some of the Ui issues (the fact that the section headers don't extend the entire width of the Screen and are gated by the global UiInsets) we still have to resolve in a Phase 2 of the tvOS Ui update.

**Comment by dnicolson** [comment]
> Yup, it works as advertised but do you think we could limit the "focusable area" to only be the "chevron" and not the entire section header?
> 
I've created a new [branch](https://github.com/Provenance-Emu/Provenance/compare/develop...dnicolson:collapse-buttons-focusable?expand=1) that shifts the focus to the collapse button.

**Comment by mrjschulte** [comment]
Conceptually this new branch does the right and desirable thing @dnicolson ! Thanks for taking another stab at this.

From a Ui design aspect we lost the "darkening effect" the Section header used to apply to unselected titles as the Section header is now completely transparent. The Focus on the Chevron also uses the square bounding box of the Chevron image, is there a way to have this be more elegant and only outline the actual Chevron itself? Do we need new Chevron artwork that reflects this?

Also, why was this value changed in **PVGameLibraryViewController+CollectionView.swift** on line 23?
        _#if os(tvOS)
             return 24.0		             return 40.0
         #else_
This change from 24 to 40 costs the space to place another title on the horizontal span and should be removed for a consistent Ui that maximizes the real estate on big TV's.

**Comment by dnicolson** [comment]
The collapse button now animates on focus, the color also changes to white which is the same for games that are focussed. I also fixed the changes in PVGameLibraryViewController+CollectionView.swift

A focus guide needs to be added to ensure that games can be selected when pressing down to a section with less than 7 items.

**Comment by mrjschulte** [comment]
Pretty great stuff with that latest update @dnicolson ! This works a treat!

**Comment by mrjschulte** [comment]
Some small bits of feedback and asks:
- There would appear to be some subtle drawing/overlay items that we probably won't be able to fix but my OCD wanted to call out. When collapsing multiple systems, which is awesome we can do now btw, some of the section separators aren't drawn.
- Any chance of adding in a small 1/4 second or 1/2 second rotation animation for the Chevron when collapsing and expanding the System Title sections?
- Do we want to add support for the collapseable behavior to the "Recently Played" and "Recently Saved sections as well?

Think you can make a new PR with the branch in question so we can track these last asks more easy and remove the current "hide collapse button" PR?

All in all, really awesome work! Thanks for the contribution.

**Comment by mrjschulte** [comment]
One more general wish: when Expanding and Collapsing sections it would be great if we could keep the current Section item selected. Currently, this selection appears to "reset" to the first Title in the GameViewLibrary which can make it a little disorienting to find your bearings in the Game Library when collapsing/expanding sections.

**Comment by dnicolson** [comment]
> * There would appear to be some subtle drawing/overlay items that we probably won't be able to fix but my OCD wanted to call out. When collapsing multiple systems, which is awesome we can do now btw, some of the section separators aren't drawn.

I also noticed this, it appears that for every second section the bottom separator is partially hidden by the title and collapse button. This problem already exists on iOS so I will look at fixing this in a different pull request.

> * Any chance of adding in a small 1/4 second or 1/2 second rotation animation for the Chevron when collapsing and expanding the System Title sections?

> �One more general wish: when Expanding and Collapsing sections it would be great if we could keep the current Section item selected. Currently, this selection appears to "reset" to the first Title in the GameViewLibrary which can make it a little disorienting to find your bearings in the Game Library when collapsing/expanding sections.

The collapse button causes the collection views to be recreated, which makes it difficult to reuse certain objects. I was able to partially get some hack to work but it may not be a viable solution.

> * Do we want to add support for the collapseable behavior to the "Recently Played" and "Recently Saved sections as well?

Maybe it could be looked at in another pull request, iOS doesn't support this yet.

> Think you can make a new PR with the branch in question so we can track these last asks more easy and remove the current "hide collapse button" PR?

I'll clean up the branch and create a pull request.

**Comment by mrjschulte** [comment]
Great, danke! Can't wait to see it.

**Pull request closed without merging**
