### PR TITLE
Use PVGameLibrary as datasource for PVGameLibraryViewController

### LINKED ISSUE #1068: Game Library not updated on initial system import (first game per system)
Games are not showing up in library when they are the first game on a system

 
### Expected: 

Game shows after import wihtin its system section.

 
### Actual: 

Section shows but is blank until refresh.

 ### Reproduce:  

1. Import a ROM for a system that is currently empty/unintitialized.
2. Refresh Game Library in order to make it show up.

#

#### APP VERSION
- [x] 1.5 *beta*
- [ ] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [x] [Building](https://git.io/vpYzv) *from Source*

#### PLATFORM
- [x] iPhone
- [x] iPad
- [x] Apple TV

#### iOS/tvOS VERSION
- [x] 12.x
- [ ] 11.x
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

### PR DESCRIPTION
**Pull request by cheif**
### What does this PR do
This builds on #1371, and further uses `PVGameLibrary` to remove logic from the ViewController, using RxRealm and RxDatasources for heavy lifting.

### How should this be manually tested
Everything should work as before, although sync-issues in PVGameLibrary should be resolved.

### What are the relevant tickets
Fixes #1068

### CODE REVIEW

**Comment by jasarien** [comment]
This PR contains the commits from #1371 - so could we close #1371 and use this as a whole?

**Comment by cheif** [comment]
@jasarien absolutely, I just made it in two steps, I guess it might be easier to review in two steps, but you decide!

**Comment by mrjschulte** [comment]
After a clean build the first few games import without issues and as expected but as soon as you run into an import conflict, with say a game for the NEC TG16 system that's also recognized as being valid for the SGX/Supergrafx system resulting in a conflict, all the subsequently imported games will not show up anymore.

**Comment by mrjschulte** [comment]
@cheif , any more ideas about resolving the issues reported with this Pr?

**Comment by cheif** [comment]
I think I know what the problem is, but I haven’t been able to sit down at my computer and look at provenance for a few weeks. Hopefully I’ll get to it soon.

**Comment by mrjschulte** [comment]
@cheif , any chance to take a look at the Issue still present in this PR?

**Comment by cheif** [comment]
@mrjschulte I've looked into this a bit now, and it seems the problem stems from `GameImporter`, if that one encounters a conflict then `encounteredConflicts` will be set to true, and we can't import stuff any more.

This isn't something that's been added in this PR, I think that maybe it's just more apparent here since the whole library-update logic is working better now, I tried it on `develop` and it happens there as well.

I'd love to take a stab at understanding `GameImporter` and fixing this bug, but that should definitely be a separate PR, care to test it out on `develop` and create a new Issue?

**Pull request merged**
