### PR TITLE
General cleanup (rebase)

### PR DESCRIPTION
**Pull request by JoeMatt**
replace #1988 with rebase

### CODE REVIEW

**Comment by Kinsman101** [comment]
Not sure why I’m getting emails from you, but can you please stop.

**Comment by jasarien** [comment]
I’m not sending them. You must be subscribed to the GitHub repo. Also… You see the unsubscribe link at the bottom of the email, right?Sent from my iPhoneOn 12 Nov 2022, at 20:40, Kinsman101 ***@***.***> wrote:﻿
Not sure why I’m getting emails from you, but can you please stop.

**Comment by Kinsman101** [comment]
I don’t even know what GitHub is. I clicked that and you have to login. I don’t have a login.

**Comment by jasarien** [comment]
😂Sent from my iPhoneOn 12 Nov 2022, at 20:59, Kinsman101 ***@***.***> wrote:﻿
I don’t even know what GitHub is. I clicked that and you have to login. I don’t have a login.

**Comment by JoeMatt** [comment]
https://github.com/Kinsman101

Someone used your email then.

**Pull request merged**
