### PR TITLE
Fix tvOS tables

### PR DESCRIPTION
**Pull request by dnicolson**
### What does this PR do
This pull request stops the tvOS table cells from vertically scrolling and other fixes.

### CODE REVIEW

**Review by JoeMatt — APPROVED** [review]

**Comment by JoeMatt** [comment]
won't be in next release, but one after.

**Comment by mrjschulte** [comment]
Hey guys, love the tvOS updates, but for tvOS Ui/Ux related items such as foregoing the use of the previously set FontSizes et al to something else, could we please get before and after screenshots showing the differences?

**Comment by dnicolson** [comment]
Before and after changes in [48b066e](https://github.com/Provenance-Emu/Provenance/pull/2047/commits/48b066e3eba49518ed2e46a7fbabb29269a2956d):
Screenshot 2022-12-10 at 19 27 20Screenshot 2022-12-10 at 19 28 13

The other commits do not make any visual changes, they just fix the table scrolling behavior.

**Comment by JoeMatt** [comment]
merged in b3a9588604f699ec457f65040d6919cbb43da6f4

**Pull request closed without merging**
