### PR TITLE
[WIP] Play! PS2 Core

### PR DESCRIPTION
**Pull request by JoeMatt**
### What does this PR do

Add support for [Play!](https://github.com/jpd002/Play-)

### CODE REVIEW

**Comment by vitkuzmenko** [comment]
Hello! Do you plan to complete this feature?

**Comment by JoeMatt** [comment]
> Hello! Do you plan to complete this feature?

Eventually, of course. Looking for help if you’re interested.

**Comment by vitkuzmenko** [comment]
Hello! I successfully install develop branch but when i import game and try to start it, i see alert "Core for game not found". May be incorrect game image?

**Comment by JoeMatt** [comment]
> Hello! I successfully install develop branch but when i import game and try to start it, i see alert "Core for game not found". May be incorrect game image?

this core is in dev, not working. It's disabled by default for that reason.

**Comment by jpike88** [comment]
Documentation says PS2 is supported though... is that accidental

**Pull request merged**
