### PR TITLE
Fix Azure CI

### PR DESCRIPTION
**Pull request by cheif**
### What does this PR do
Fixing so that CI is run on Azure correctly.

I've also been looking into Travis, but there we have a problem with `carthage bootstrap` timing out, and I didn't look into using the `rome` caching thingy.

I'm not sure what the reason for having Azure + Travis + Bitrise is though?

### CODE REVIEW

**Comment by jasarien** [comment]
Still failed: https://dev.azure.com/mail0628/Provenance%20EMU/_build/results?buildId=563&view=results

**Comment by cheif** [comment]
Yup, but AFAIK I'll have to create a PR to get things running?

**Comment by jasarien** [comment]
I’m not sure what you mean? This is a PR, and the build will run with your changes each time. So if your changes fix the issue, the build should succeed, right?

**Comment by cheif** [comment]
Exactly, but I’ll need to test it in the PR, thus it’ll probably be failing for a while :)

**Comment by cheif** [comment]
This is now ready to be merged, if I take a stab on Bitrise/Travis that'll be another PR, but I'm not sure we should have so many CI:s?

**Comment by cheif** [comment]
Partially fixes #1237

**Comment by jasarien** [comment]
Agreed. I don’t know why we even have more than one. Maybe after one didn’t work someone just added more to see if they worked!? 🤷‍♂️😂 if we have one working, stick with it, and remove the others, I guess.

**Comment by jasarien** [comment]
I noticed some changes were made to project files. Does this affect compiling outside the context of CI at all?

**Comment by cheif** [comment]
@jasarien Yeah, there was a problem building `gen68k` from CLI, and internet said to change it from `.tool` to `.application` and that solved it, I haven't seen anything breaking on my side, but then I'm not really sure what `gen68k` do in the first place.

Other than that it's just test related, switching to using a test plan so that all tests can be run when testing the `Provenance` target and adding some missing frameworks, basically just making sure that running tests work.

**Comment by jasarien** [comment]
I don’t know for sure, but if I had to guess I’d would say that the gen68k program generates the 68000 assembly used by the emulator to do stuff. Just a guess though.

**Pull request merged**
