### PR TITLE
Update MednafenGameCore.mm

### PR DESCRIPTION
**Pull request by mrjschulte**
This patch adds support for displaying the full horizontal overscan in games and also enables the PCE Core to display the games at the full intended height.

### CODE REVIEW

**Comment by mrjschulte** [comment]
Forgot to add, this also ups the quality of the Audio resampler used for PCE games.

**Comment by mrjschulte** [comment]
PLEASE HOLD ON MERGING THIS, for now, as we track down the other issues with the PCE conflict resolving on #1414

**Comment by mrjschulte** [comment]
Ok to Merge, Provenance still crashes per #1414 . This PR is not related.

**Comment by mrjschulte** [comment]
@JoeMatt @jasarien any thoughts?

**Review by jasarien — APPROVED** [review]

**Pull request merged**
