### PR TITLE
Fix some Xcode 12 warnings

### PR DESCRIPTION
**Pull request by dnicolson**
### What does this PR do
This pull request resolves some warnings shown in Xcode 12.

### Where should the reviewer start
Look at each commit individually.

### Any background context you want to provide
- b9580a6 upgrades [TPCircularBuffer](https://github.com/michaeltyson/TPCircularBuffer), some additional changes were made including the changes from https://github.com/OpenEmu/OpenEmu/commit/76b6b9f33411fb6e173e74fbf60fcff3e6e01f7a to prevent a crash. This is admittedly done without knowing the full implications, so I am happy to remove the commit if there is any uncertainty.
- e12dc95 contains the recommended updates Xcode made.

### CODE REVIEW

**Comment by mrjschulte** [comment]
Thanks @dnicolson ! Looks like we may have an issue with the UIActionSheet items that were removed as part of https://github.com/Provenance-Emu/Provenance/pull/1477/commits/1f693317eeefb147e5b5d8a47681e7d082c56166

 Do you perhaps want to take a quick look at the following error we see when compiling this PR from scratch, I used Xcode 11.6 if it matters:

_/Provenance/dnicolson/fix-buildtime-warnings/Provenance/ProvenanceTV-Bridging-Header.h:22:9: error: 'UIActionSheet+BlockAdditions.h' file not found
#import "UIActionSheet+BlockAdditions.h"
        ^
1 error generated.
<unknown>:0: error: failed to emit precompiled header 'Provenance-dhmltoljggnkqjcazwaxwbtexuvx/Build/Intermediates.noindex/PrecompiledHeaders/ProvenanceTV-Bridging-Header-swift_1JX11ZTOYB9H4-clang_LZX4XXBN2SH4.pch' for bridging header '/Provenance/dnicolson/fix-buildtime-warnings/Provenance/ProvenanceTV-Bridging-Header.h'_

**Review by mrjschulte — CHANGES_REQUESTED** [review]
Looks like this may be causing us a build issue. I can't get this to compile for tvOS.

**Comment by mrjschulte** [comment]
Just to update this PR Comment with the news that this builds fine as -is for iOS. So definitely looks like a tvOS related item.

**Comment by mrjschulte** [comment]
Looks like the offending item lives here on line 22:
https://github.com/Provenance-Emu/Provenance/blob/develop/ProvenanceTV-Bridging-Header.h

**Comment by mrjschulte** [comment]
#1478 also calls out the Bridging header for removal so we could take whichever PR gets around to fixing that issue first and use the other items in this PR accordingly.

If possible it could be best to build this out for tvOS on your side as well @dnicolson? 

If you have the time there are other items that fail on the tvOS build besides the bridging header item that will block the merging of this PR. 

_/Provenance/dnicolson/fix-buildtime-warnings/Provenance/Provenance/Settings/Custom Rows/SegueNavigationRow.swift:22:15: Expression type 'NavigationRow<SystemSettingsCell>' is ambiguous without more context_

**Comment by dnicolson** [comment]
@mrjschulte thanks for the comments.

643d04b has been removed due to tvOS incompatibility for now.

1f69331 has been removed in favour of #1478.

**Comment by mrjschulte** [comment]
Thanks for the quick fixes on these @dnicolson . This PR now builds the release schemes for iOS and tvOS as expected. 
Merged!

**Pull request merged**
